// Field schema for the visual settings window. Pure data — no DOM, no
// Electron. The renderer (settings.mjs) renders one control per field from
// these descriptors; tests assert the schema covers every leaf of
// DEFAULT_CONFIG/SCHEMA in src/config.mjs with matching ranges and enum
// options, so the UI cannot drift from the validated configuration shape.
//
// Field types:
//   boolean  -> switch, bound to a boolean
//   enum     -> select, options = [{ value, label }]
//   number   -> number input, min/max/step mirror config.mjs validation
//   text     -> text input
//   password -> password input (never sent back by get-state)
//   icon     -> visual icon picker inside the custom-command list editor
//   commands -> list editor for menu.customCommands (subfields below)
//
// Groups marked 'static' render informational content only; fields marked
// 'external' do not map onto config.json (credentials live in a separate
// 0600 file and are handled by the credentials sub-section of the weather
// group).

// 24x24 linear stroke icon set for the settings window navigation and the
// header brand mark. Mirrors the context-menu ICONS style (fill none, 1.5
// stroke, round caps) so the settings surface shares the menu's iconography.
export const SETTINGS_ICONS = Object.freeze({
  sliders: '<path d="M4 7h9"/><path d="M17 7h3"/><circle cx="15" cy="7" r="2"/><path d="M4 12h3"/><path d="M11 12h9"/><circle cx="9" cy="12" r="2"/><path d="M4 17h9"/><path d="M17 17h3"/><circle cx="15" cy="17" r="2"/>',
  image: '<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8.5" cy="9.5" r="1.5"/><path d="M21 15l-5-5-9 9"/>',
  palette: '<circle cx="12" cy="12" r="9"/><circle cx="8" cy="9" r="1"/><circle cx="14" cy="7.5" r="1"/><circle cx="16.5" cy="12" r="1"/><circle cx="12.5" cy="16.5" r="1"/>',
  music: '<path d="M9 18V5l10-2v13"/><circle cx="6.5" cy="18" r="2.5"/><circle cx="16.5" cy="16" r="2.5"/>',
  move: '<path d="M5 9l-3 3 3 3"/><path d="M9 5l3-3 3 3"/><path d="M15 19l-3 3-3-3"/><path d="M19 9l3 3-3 3"/><path d="M2 12h20"/><path d="M12 2v20"/>',
  layout: '<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18"/><path d="M12 9v11"/>',
  cloud: '<path d="M7 18a4 4 0 0 1-.9-7.9 5.5 5.5 0 0 1 10.6 1.3A3.5 3.5 0 0 1 16.5 18z"/>',
  menu: '<rect x="4" y="4" width="16" height="16" rx="2"/><path d="M8 9h8"/><path d="M8 12h8"/><path d="M8 15h5"/>',
  info: '<circle cx="12" cy="12" r="9"/><path d="M12 11v5"/><path d="M12 8h.01"/>',
  settings: '<path d="M4 7h10"/><path d="M18 7h2"/><path d="M4 12h4"/><path d="M12 12h8"/><path d="M4 17h12"/><path d="M20 17h0"/><circle cx="16" cy="7" r="2"/><circle cx="10" cy="12" r="2"/><circle cx="18" cy="17" r="2"/>',
});

const COMMAND_MODE_OPTIONS = Object.freeze([
  { value: 'background', label: '后台执行' },
  { value: 'terminal', label: '终端执行' },
]);

// Editable subfields of a custom menu command. The unique id is generated by
// the UI (cmd-1, cmd-2, …) and shown read-only, so it is not part of this
// list; the icon subfield is rendered as a visual picker, not a text input.
// Editable subfields of a custom menu command; the icon is handled by the
// visual picker (first column), and the unique id is auto-managed by the UI
// and hidden, so neither is an editable subfield here.
const COMMAND_SUBFIELDS = Object.freeze([
  { key: 'label', label: '显示名称', type: 'text', placeholder: '菜单显示文字' },
  { key: 'command', label: '命令', type: 'text', placeholder: '如 xdg-open ~/Downloads' },
  { key: 'mode', label: '执行模式', type: 'enum', options: COMMAND_MODE_OPTIONS },
]);

// Ordered groups rendered in the settings window navigation and content area.
// 'static' groups are informational only; 'external' fields live outside
// config.json (credentials are stored in a separate 0600 file).
export const SETTINGS_GROUPS = Object.freeze([
  {
    id: 'interaction',
    title: '交互',
    icon: 'sliders',
    fields: [
      {
        key: 'mouse.buttonsEnabled',
        label: '鼠标按键',
        type: 'boolean',
        description: '是否接收鼠标按键；关闭后壁纸窗口穿透鼠标，右键菜单与设置入口不可用',
      },
      {
        key: 'mouse.interactionEnabled',
        label: '鼠标交互',
        type: 'boolean',
        description: '是否用指针移动驱动视差与信息面板；关闭后仅停止视差响应，仍可打开右键菜单',
      },
    ],
  },
  {
    id: 'wallpaper',
    title: '壁纸',
    icon: 'image',
    fields: [
      {
        key: 'wallpaper.mode',
        label: '壁纸模式',
        type: 'enum',
        options: [
          { value: 'kde', label: '跟随 KDE' },
          { value: 'manual', label: '手动图片' },
        ],
        description: '切换后会经配置热加载立即生效',
      },
    ],
  },
  {
    id: 'appearance',
    title: '外观',
    icon: 'palette',
    fields: [
      {
        key: 'color.mode',
        label: '强调色来源',
        type: 'enum',
        options: [
          { value: 'default', label: '默认' },
          { value: 'kde', label: '跟随 KDE 强调色' },
          { value: 'wallpaper', label: '从壁纸取色' },
          { value: 'hybrid', label: '混合（优先壁纸，回退 KDE）' },
        ],
      },
      {
        key: 'color.transitionDurationMs',
        label: '强调色过渡时长',
        type: 'number',
        min: 0,
        max: 5000,
        step: 50,
        unit: 'ms',
        description: '0 为立即切换；系统启用减少动态效果时强制为 0',
      },
      {
        key: 'appearance.mode',
        label: '明暗模式',
        type: 'enum',
        options: [
          { value: 'light', label: '浅色' },
          { value: 'dark', label: '深色' },
          { value: 'system', label: '跟随系统' },
        ],
      },
      {
        key: 'appearance.dark.wallpaperBrightness',
        label: '深色模式壁纸亮度',
        type: 'number',
        min: 0.2,
        max: 1,
        step: 0.01,
        description: '深色模式下壁纸的最终显示亮度倍率；1 表示不压暗',
      },
    ],
  },
  {
    id: 'audio',
    title: '音频',
    icon: 'music',
    fields: [
      { key: 'audio.enabled', label: '音频可视化', type: 'boolean', description: '启用或停止输出设备 monitor 频谱' },
      { key: 'audio.gain', label: '频谱增益', type: 'number', min: 0.25, max: 4, step: 0.05 },
      { key: 'audio.silenceDelayMs', label: '静音等待', type: 'number', min: 0, max: 5000, step: 50, unit: 'ms', description: '静音后保持曲线的等待时间' },
      { key: 'audio.fadeOutMs', label: '淡出时长', type: 'number', min: 0, max: 3000, step: 50, unit: 'ms' },
      { key: 'audio.fadeInMs', label: '淡入时长', type: 'number', min: 0, max: 3000, step: 50, unit: 'ms' },
    ],
  },
  {
    id: 'motion',
    title: '运动与视差',
    icon: 'move',
    fields: [
      { key: 'motion.interactionSpeed', label: '交互追随速度', type: 'number', min: 0.01, step: 0.05 },
      { key: 'motion.returnSpeed', label: '回归速度', type: 'number', min: 0.01, step: 0.05 },
      { key: 'motion.driftSpeed', label: '漂移速度', type: 'number', min: 0.01, step: 0.05 },
      { key: 'motion.deadZonePx', label: '指针死区', type: 'number', min: 0, step: 1, unit: 'px', description: '过滤细小指针抖动的滑动死区' },
      { key: 'motion.horizontalPanPercent', label: '水平平移上限', type: 'number', min: 0, step: 0.1, unit: '%', description: '占视口宽度的比例' },
      { key: 'motion.verticalPanPercent', label: '垂直平移上限', type: 'number', min: 0, step: 0.1, unit: '%', description: '占视口高度的比例' },
      { key: 'motion.maxRotationDegrees', label: '最大旋转角度', type: 'number', min: 0, step: 0.1, unit: '°' },
      { key: 'motion.pauseWhenFullscreen', label: '全屏覆盖时暂停', type: 'boolean', description: '显示器被全屏/最大化窗口覆盖时暂停该屏移动与渲染，窗口恢复后自动继续' },
      { key: 'frameRate.interactive', label: '交互帧率', type: 'number', min: 1, max: 180, step: 1, unit: 'FPS', description: '交互、回归、面板展开与动画阶段的目标帧率' },
      { key: 'frameRate.drift', label: '漂移帧率', type: 'number', min: 1, max: 180, step: 1, unit: 'FPS', description: '面板收起且完全静止时的待机漂移帧率' },
    ],
  },
  {
    id: 'panel',
    title: '信息面板',
    icon: 'layout',
    fields: [
      { key: 'panel.autoExpandHide', label: '自动展开收起', type: 'boolean', description: '按鼠标距离自动展开并延迟收起' },
      { key: 'panel.expandTriggerDistancePx', label: '展开触发距离', type: 'number', min: 0, step: 1, unit: 'px', description: '触发下一块面板展开所需的累计指针移动' },
      { key: 'panel.collapseDelaySeconds', label: '收起等待时间', type: 'number', min: 0, step: 0.5, unit: 's', description: '无交互后开始收起的等待时间' },
      { key: 'panel.expanded', label: '固定展开', type: 'boolean', description: '禁用自动模式时使用的固定展开状态' },
      { key: 'panel.collapsedOpacity', label: '收起最低不透明度', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'panel.animation.staggerDelayMs', label: '动画错开时间', type: 'number', min: 0, step: 10, unit: 'ms' },
      { key: 'panel.animation.durationMs', label: '单块动画时长', type: 'number', min: 400, step: 10, unit: 'ms', description: '包含两次回弹的单块面板动画时长' },
    ],
  },
  {
    id: 'weather',
    title: '天气',
    icon: 'cloud',
    fields: [
      {
        key: 'weather.location.mode',
        label: '定位模式',
        type: 'enum',
        options: [
          { value: 'auto', label: '自动（XDG Desktop Portal 定位）' },
          { value: 'fixed', label: '固定坐标' },
        ],
      },
      { key: 'weather.location.latitude', label: '纬度', type: 'number', min: -90, max: 90, step: 0.0001, nullable: true, description: 'fixed 模式必须与经度同时提供' },
      { key: 'weather.location.longitude', label: '经度', type: 'number', min: -180, max: 180, step: 0.0001, nullable: true },
      { key: 'weather.location.fallbackLocationId', label: '回退 LocationID', type: 'text', description: '自动定位与缓存均失败时使用的和风 LocationID' },
      { key: 'weather.tideStationId', label: '潮汐观测站 ID', type: 'text' },
      // External credentials: stored in weather-credentials.json (0600), not
      // config.json. Rendered by the credentials sub-section of this group.
      { key: 'apiHost', label: 'API Host', type: 'text', external: true, placeholder: 'your-project-host.qweatherapi.com', description: '只填 HTTPS 域名，不包含协议、路径或查询参数' },
      { key: 'apiKey', label: 'API Key', type: 'password', external: true, placeholder: '已保存时留空可保留现有 Key', description: '仅主进程读取，不会进入 renderer、日志或缓存' },
    ],
  },
  {
    id: 'menu',
    title: '右键菜单',
    icon: 'menu',
    fields: [
      { key: 'menu.avoidObstacles', label: '避障', type: 'boolean', description: '开启后菜单避开屏幕边缘与 Plasma 面板/应用栏；关闭后菜单精确显示在右键位置' },
      { key: 'menu.closeOnFocusChange', label: '进入其他应用时收起', type: 'boolean', description: '指针离开壁纸或切换到其他应用时自动收起' },
      { key: 'menu.autoCloseMs', label: '自动收起兜底', type: 'number', min: 0, step: 100, unit: 'ms', description: '打开后无人操作超过该时长自动关闭；0 关闭此兜底' },
      { key: 'menu.terminal', label: '终端模拟器', type: 'text', placeholder: '留空自动检测' },
      { key: 'menu.customCommands', label: '自定义命令', type: 'commands', fields: COMMAND_SUBFIELDS, description: '终端执行的命令默认执行完自动退出终端；可在「更多」中关闭' },
    ],
  },
  {
    id: 'about',
    title: '关于',
    icon: 'info',
    static: true,
  },
]);

// Dot-path access helpers shared by the renderer and tests.
export function getPath(object, key) {
  return key.split('.').reduce((value, part) => (value == null ? undefined : value[part]), object);
}

export function setPath(object, key, value) {
  const parts = key.split('.');
  const last = parts.pop();
  const target = parts.reduce((current, part) => {
    if (current[part] == null || typeof current[part] !== 'object') current[part] = {};
    return current[part];
  }, object);
  target[last] = value;
}
