// Field schema for the visual settings window. Pure data — no DOM, no
// Electron. The renderer (settings.mjs) renders one control per field from
// these descriptors; tests assert the schema covers every leaf of
// DEFAULT_CONFIG/SCHEMA in src/config.mjs with matching ranges and enum
// options, so the UI cannot drift from the validated configuration shape.
//
// Field types:
//   boolean  -> switch, bound to a boolean
//   enum     -> select, options = [{ value, label }]
//   number   -> number input, min/max/step mirror config.mjs validation
//   text     -> text input
//   password -> password input (never sent back by get-state)
//   icon     -> visual icon picker inside the custom-command list editor
//   commands -> list editor for menu.customCommands (subfields below)
//
// Groups marked 'static' render informational content only; fields marked
// 'external' do not map onto config.json (credentials live in a separate
// 0600 file and are handled by the credentials sub-section of the weather
// group).

// 24x24 linear stroke icon set for the settings window navigation and the
// header brand mark. Mirrors the context-menu ICONS style (fill none, 1.5
// stroke, round caps) so the settings surface shares the menu's iconography.
export const SETTINGS_ICONS = Object.freeze({
  sliders: '<path d="M4 7h9"/><path d="M17 7h3"/><circle cx="15" cy="7" r="2"/><path d="M4 12h3"/><path d="M11 12h9"/><circle cx="9" cy="12" r="2"/><path d="M4 17h9"/><path d="M17 17h3"/><circle cx="15" cy="17" r="2"/>',
  image: '<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8.5" cy="9.5" r="1.5"/><path d="M21 15l-5-5-9 9"/>',
  palette: '<circle cx="12" cy="12" r="9"/><circle cx="8" cy="9" r="1"/><circle cx="14" cy="7.5" r="1"/><circle cx="16.5" cy="12" r="1"/><circle cx="12.5" cy="16.5" r="1"/>',
  music: '<path d="M9 18V5l10-2v13"/><circle cx="6.5" cy="18" r="2.5"/><circle cx="16.5" cy="16" r="2.5"/>',
  move: '<path d="M5 9l-3 3 3 3"/><path d="M9 5l3-3 3 3"/><path d="M15 19l-3 3-3-3"/><path d="M19 9l3 3-3 3"/><path d="M2 12h20"/><path d="M12 2v20"/>',
  layout: '<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18"/><path d="M12 9v11"/>',
  cloud: '<path d="M7 18a4 4 0 0 1-.9-7.9 5.5 5.5 0 0 1 10.6 1.3A3.5 3.5 0 0 1 16.5 18z"/>',
  menu: '<rect x="4" y="4" width="16" height="16" rx="2"/><path d="M8 9h8"/><path d="M8 12h8"/><path d="M8 15h5"/>',
  info: '<circle cx="12" cy="12" r="9"/><path d="M12 11v5"/><path d="M12 8h.01"/>',
  settings: '<path d="M4 7h10"/><path d="M18 7h2"/><path d="M4 12h4"/><path d="M12 12h8"/><path d="M4 17h12"/><path d="M20 17h0"/><circle cx="16" cy="7" r="2"/><circle cx="10" cy="12" r="2"/><circle cx="18" cy="17" r="2"/>',
});

const COMMAND_MODE_OPTIONS = Object.freeze([
  { value: 'background', label: '后台执行' },
  { value: 'terminal', label: '终端执行' },
]);

// Editable subfields of a custom menu command. The unique id is generated by
// the UI (cmd-1, cmd-2, …) and shown read-only, so it is not part of this
// list; the icon subfield is rendered as a visual picker, not a text input.
// Editable subfields of a custom menu command; the icon is handled by the
// visual picker (first column), and the unique id is auto-managed by the UI
// and hidden, so neither is an editable subfield here.
const COMMAND_SUBFIELDS = Object.freeze([
  { key: 'label', label: '显示名称', type: 'text', placeholder: '菜单显示文字' },
  { key: 'command', label: '命令', type: 'text', placeholder: '如 xdg-open ~/Downloads' },
  { key: 'mode', label: '执行模式', type: 'enum', options: COMMAND_MODE_OPTIONS },
]);

// Ordered groups rendered in the settings window navigation and content area.
// 'static' groups are informational only; 'external' fields live outside
// config.json (credentials are stored in a separate 0600 file).
export const SETTINGS_GROUPS = Object.freeze([
  {
    id: 'interaction',
    title: '交互',
    icon: 'sliders',
    fields: [
      {
        key: 'mouse.buttonsEnabled',
        label: '鼠标按键',
        type: 'boolean',
        description: '是否接收鼠标按键；关闭后壁纸窗口穿透鼠标，右键菜单与设置入口不可用',
      },
      {
        key: 'mouse.interactionEnabled',
        label: '鼠标交互',
        type: 'boolean',
        description: '是否用指针移动驱动视差与信息面板；关闭后仅停止视差响应，仍可打开右键菜单',
      },
    ],
  },
  {
    id: 'wallpaper',
    title: '壁纸',
    icon: 'image',
    fields: [
      {
        key: 'wallpaper.mode',
        label: '壁纸模式',
        type: 'enum',
        options: [
          { value: 'kde', label: '跟随 KDE' },
          { value: 'manual', label: '手动图片' },
        ],
        description: '切换后会经配置热加载立即生效',
      },
      {
        key: 'wallpaper.fit',
        label: '壁纸适配',
        type: 'enum',
        options: [
          { value: 'cover', label: '填充（裁剪）' },
          { value: 'contain', label: '完整显示（留白）' },
          { value: 'stretch', label: '拉伸' },
          { value: 'center', label: '居中' },
        ],
      },
      {
        key: 'wallpaper.crossfadeMs',
        label: '切换过渡',
        type: 'number',
        min: 0,
        max: 1200,
        step: 10,
        unit: 'ms',
        description: '壁纸切换时的交叉淡化时长',
      },
    ],
  },
  {
    id: 'appearance',
    title: '外观',
    icon: 'palette',
    fields: [
      {
        key: 'color.mode',
        label: '强调色来源',
        type: 'enum',
        options: [
          { value: 'default', label: '默认' },
          { value: 'kde', label: '跟随 KDE 强调色' },
          { value: 'wallpaper', label: '从壁纸取色' },
          { value: 'hybrid', label: '混合（优先壁纸，回退 KDE）' },
        ],
      },
      {
        key: 'color.transitionDurationMs',
        label: '强调色过渡时长',
        type: 'number',
        min: 0,
        max: 5000,
        step: 50,
        unit: 'ms',
        description: '0 为立即切换；系统启用减少动态效果时强制为 0',
      },
      {
        key: 'appearance.mode',
        label: '明暗模式',
        type: 'enum',
        options: [
          { value: 'light', label: '浅色' },
          { value: 'dark', label: '深色' },
          { value: 'system', label: '跟随系统' },
        ],
      },
      {
        key: 'appearance.dark.wallpaperBrightness',
        label: '深色模式壁纸亮度',
        type: 'number',
        min: 0.2,
        max: 1,
        step: 0.01,
        description: '深色模式下壁纸的最终显示亮度倍率；1 表示不压暗',
      },
    ],
  },
  {
    id: 'audio',
    title: '音频',
    icon: 'music',
    fields: [
      { key: 'audio.enabled', label: '音频可视化', type: 'boolean', description: '启用或停止输出设备 monitor 频谱' },
      { key: 'audio.gain', label: '频谱增益', type: 'number', min: 0.25, max: 4, step: 0.05 },
      { key: 'audio.silenceDelayMs', label: '静音等待', type: 'number', min: 0, max: 5000, step: 50, unit: 'ms', description: '静音后保持曲线的等待时间' },
      { key: 'audio.fadeOutMs', label: '淡出时长', type: 'number', min: 0, max: 3000, step: 50, unit: 'ms' },
      { key: 'audio.fadeInMs', label: '淡入时长', type: 'number', min: 0, max: 3000, step: 50, unit: 'ms' },
    ],
  },
  {
    id: 'motion',
    title: '运动与视差',
    icon: 'move',
    fields: [
      { key: 'motion.interactionSpeed', label: '交互追随速度', type: 'number', min: 0.01, step: 0.05 },
      { key: 'motion.returnSpeed', label: '回归速度', type: 'number', min: 0.01, step: 0.05 },
      { key: 'motion.driftSpeed', label: '漂移速度', type: 'number', min: 0.01, step: 0.05 },
      { key: 'motion.deadZonePx', label: '指针死区', type: 'number', min: 0, step: 1, unit: 'px', description: '过滤细小指针抖动的滑动死区' },
      { key: 'motion.horizontalPanPercent', label: '水平平移上限', type: 'number', min: 0, step: 0.1, unit: '%', description: '占视口宽度的比例' },
      { key: 'motion.verticalPanPercent', label: '垂直平移上限', type: 'number', min: 0, step: 0.1, unit: '%', description: '占视口高度的比例' },
      { key: 'motion.maxRotationDegrees', label: '最大旋转角度', type: 'number', min: 0, step: 0.1, unit: '°' },
      { key: 'motion.pauseWhenFullscreen', label: '全屏覆盖时暂停', type: 'boolean', description: '显示器被全屏/最大化窗口覆盖时暂停该屏移动与渲染，窗口恢复后自动继续' },
      { key: 'frameRate.interactive', label: '交互帧率', type: 'number', min: 1, max: 180, step: 1, unit: 'FPS', description: '交互、回归、面板展开与动画阶段的目标帧率' },
      { key: 'frameRate.drift', label: '漂移帧率', type: 'number', min: 1, max: 180, step: 1, unit: 'FPS', description: '面板收起且完全静止时的待机漂移帧率' },
    ],
  },
  {
    id: 'panel',
    title: '信息面板',
    icon: 'layout',
    fields: [
      { key: 'panel.autoExpandHide', label: '自动展开收起', type: 'boolean', description: '按鼠标距离自动展开并延迟收起' },
      { key: 'panel.expandTriggerDistancePx', label: '展开触发距离', type: 'number', min: 0, step: 1, unit: 'px', description: '触发下一块面板展开所需的累计指针移动' },
      { key: 'panel.collapseDelaySeconds', label: '收起等待时间', type: 'number', min: 0, step: 0.5, unit: 's', description: '无交互后开始收起的等待时间' },
      { key: 'panel.expanded', label: '固定展开', type: 'boolean', description: '禁用自动模式时使用的固定展开状态' },
      { key: 'panel.collapsedOpacity', label: '收起最低不透明度', type: 'number', min: 0, max: 1, step: 0.01 },
      { key: 'panel.borderRadius', label: '卡片圆角', type: 'number', min: 0, max: 24, step: 1, unit: 'px', description: '信息卡圆角半径，0 为直角' },
      { key: 'panel.surfaceOpacity', label: '卡片不透明度', type: 'number', min: 0.2, max: 1, step: 0.02, description: '信息卡表面不透明度，0.2-1' },
      { key: 'panel.shadowIntensity', label: '重点色装饰尺寸', type: 'number', min: 0, max: 1, step: 0.05 },
      { key: 'panel.height', label: '信息面板高度', type: 'number', min: 240, max: 560, step: 10, unit: 'px', description: '缩放悬浮与视差运动幅度, 240px - 560px' },
      { key: 'panel.animation.staggerDelayMs', label: '动画错开时间', type: 'number', min: 0, step: 10, unit: 'ms' },
      { key: 'panel.animation.durationMs', label: '单块动画时长', type: 'number', min: 400, step: 10, unit: 'ms', description: '包含两次回弹的单块面板动画时长' },
    ],
  },
  {
    id: 'weather',
    title: '天气',
    icon: 'cloud',
    fields: [
      {
        key: 'weather.location.mode',
        label: '定位模式',
        type: 'enum',
        options: [
          { value: 'auto', label: '自动（XDG Desktop Portal 定位）' },
          { value: 'fixed', label: '固定坐标' },
        ],
      },
      { key: 'weather.location.latitude', label: '纬度', type: 'number', min: -90, max: 90, step: 0.0001, nullable: true, description: 'fixed 模式必须与经度同时提供' },
      { key: 'weather.location.longitude', label: '经度', type: 'number', min: -180, max: 180, step: 0.0001, nullable: true },
      { key: 'weather.location.fallbackLocationId', label: '回退 LocationID', type: 'text', description: '自动定位与缓存均失败时使用的和风 LocationID' },
      { key: 'weather.tideStationId', label: '潮汐观测站 ID', type: 'text' },
      // External credentials: stored in weather-credentials.json (0600), not
      // config.json. Rendered by the credentials sub-section of this group.
      { key: 'apiHost', label: 'API Host', type: 'text', external: true, placeholder: 'your-project-host.qweatherapi.com', description: '只填 HTTPS 域名，不包含协议、路径或查询参数' },
      { key: 'apiKey', label: 'API Key', type: 'password', external: true, placeholder: '已保存时留空可保留现有 Key', description: '仅主进程读取，不会进入 renderer、日志或缓存' },
    ],
  },
  {
    id: 'menu',
    title: '右键菜单',
    icon: 'menu',
    fields: [
      { key: 'menu.avoidObstacles', label: '避障', type: 'boolean', description: '开启后菜单避开屏幕边缘与 Plasma 面板/应用栏；关闭后菜单精确显示在右键位置' },
      { key: 'menu.closeOnFocusChange', label: '进入其他应用时收起', type: 'boolean', description: '指针离开壁纸或切换到其他应用时自动收起' },
      { key: 'menu.autoCloseMs', label: '自动收起兜底', type: 'number', min: 0, step: 100, unit: 'ms', description: '打开后无人操作超过该时长自动关闭；0 关闭此兜底' },
      { key: 'menu.terminal', label: '终端模拟器', type: 'text', placeholder: '留空自动检测' },
      { key: 'menu.customCommands', label: '自定义命令', type: 'commands', fields: COMMAND_SUBFIELDS, description: '终端执行的命令默认执行完自动退出终端；可在「更多」中关闭' },
    ],
  },
  {
    id: 'about',
    title: '关于',
    icon: 'info',
    static: true,
  },
]);

// Subdivisions inside large groups. Each entry is rendered as a sub-card
// within the same navigation page; fieldKeys reference SETTINGS_GROUPS fields
// (including external ones). Groups without an entry stay as a single card.
export const SETTINGS_SECTIONS = Object.freeze({
  wallpaper: Object.freeze([
    { id: 'wallpaper-settings', title: '壁纸设置', fieldKeys: Object.freeze(['wallpaper.mode', 'wallpaper.fit', 'wallpaper.crossfadeMs']) },
    { id: 'wallpaper-gallery', title: '壁纸画廊', fieldKeys: Object.freeze([]), gallery: true },
  ]),
  appearance: Object.freeze([
    { id: 'appearance-accent', title: '强调色', fieldKeys: Object.freeze(['color.mode', 'color.transitionDurationMs']) },
    { id: 'appearance-theme', title: '明暗模式', fieldKeys: Object.freeze(['appearance.mode', 'appearance.dark.wallpaperBrightness']) },
  ]),
  audio: Object.freeze([
    { id: 'audio-core', title: '播放与增益', fieldKeys: Object.freeze(['audio.enabled', 'audio.gain']) },
    { id: 'audio-timing', title: '静音与淡入淡出', fieldKeys: Object.freeze(['audio.silenceDelayMs', 'audio.fadeOutMs', 'audio.fadeInMs']) },
  ]),
  motion: Object.freeze([
    { id: 'motion-speed', title: '运动速度', fieldKeys: Object.freeze(['motion.interactionSpeed', 'motion.returnSpeed', 'motion.driftSpeed', 'motion.deadZonePx']) },
    { id: 'motion-parallax', title: '视差幅度', fieldKeys: Object.freeze(['motion.horizontalPanPercent', 'motion.verticalPanPercent', 'motion.maxRotationDegrees']) },
    { id: 'motion-frame', title: '帧率与暂停', fieldKeys: Object.freeze(['motion.pauseWhenFullscreen', 'frameRate.interactive', 'frameRate.drift']) },
  ]),
  panel: Object.freeze([
    { id: 'panel-behavior', title: '交互行为', fieldKeys: Object.freeze(['panel.autoExpandHide', 'panel.expandTriggerDistancePx', 'panel.collapseDelaySeconds', 'panel.expanded']) },
    { id: 'panel-look', title: '卡片外观', fieldKeys: Object.freeze(['panel.collapsedOpacity', 'panel.borderRadius', 'panel.surfaceOpacity', 'panel.shadowIntensity', 'panel.height']) },
    { id: 'panel-animation', title: '动画', fieldKeys: Object.freeze(['panel.animation.staggerDelayMs', 'panel.animation.durationMs']) },
  ]),
  weather: Object.freeze([
    { id: 'weather-location', title: '定位', fieldKeys: Object.freeze(['weather.location.mode', 'weather.location.latitude', 'weather.location.longitude', 'weather.location.fallbackLocationId']) },
    { id: 'weather-tide', title: '潮汐', fieldKeys: Object.freeze(['weather.tideStationId']) },
    { id: 'weather-credentials', title: '和风凭据', fieldKeys: Object.freeze(['apiHost', 'apiKey']) },
  ]),
  menu: Object.freeze([
    { id: 'menu-behavior', title: '菜单行为', fieldKeys: Object.freeze(['menu.avoidObstacles', 'menu.closeOnFocusChange', 'menu.autoCloseMs']) },
    { id: 'menu-terminal', title: '终端', fieldKeys: Object.freeze(['menu.terminal']) },
    { id: 'menu-commands', title: '自定义命令', fieldKeys: Object.freeze(['menu.customCommands']) },
  ]),
});

// Dot-path access helpers shared by the renderer and tests.
export function getPath(object, key) {
  return key.split('.').reduce((value, part) => (value == null ? undefined : value[part]), object);
}

export function setPath(object, key, value) {
  const parts = key.split('.');
  const last = parts.pop();
  const target = parts.reduce((current, part) => {
    if (current[part] == null || typeof current[part] !== 'object') current[part] = {};
    return current[part];
  }, object);
  target[last] = value;
}

// ---------------------------------------------------------------------------
// Validation — concise Chinese messages (精简技术风). Mirrors src/config.mjs
// ranges so the UI can show readable errors before IPC and also translate
// backend English errors.
// ---------------------------------------------------------------------------

function isEmptyValue(value) {
  return value === undefined || value === null || (typeof value === 'string' && value.trim() === '');
}

function isIntegerLike(field) {
  // Integer fields are those with integer bounds and step 1/10/50/100; treat
  // known integer keys explicitly to avoid float misclassification.
  const integerKeys = new Set([
    'wallpaper.crossfadeMs',
    'color.transitionDurationMs',
    'frameRate.interactive',
    'frameRate.drift',
    'audio.silenceDelayMs',
    'audio.fadeOutMs',
    'audio.fadeInMs',
    'panel.expandTriggerDistancePx',
    'panel.borderRadius',
    'panel.height',
    'panel.animation.staggerDelayMs',
    'panel.animation.durationMs',
    'menu.autoCloseMs',
  ]);
  if (field && integerKeys.has(field.key)) return true;
  if (field && field.step !== undefined && Number.isInteger(field.step) && field.step >= 1) {
    // Heuristic: step 1,10,50,100 etc. implies integer
    return true;
  }
  return false;
}

export function validateField(field, value, draft) {
  if (!field) return null;
  // boolean / enum are not free-fill numbers but still validate
  if (field.type === 'boolean') {
    if (typeof value !== 'boolean') return '需为布尔值';
    return null;
  }
  if (field.type === 'enum') {
    const allowed = (field.options ?? []).map((o) => o.value);
    if (!allowed.includes(value)) return `需为 ${allowed.join(' / ')}`;
    return null;
  }
  if (field.type === 'number') {
    // nullable latitude/longitude: null is valid when not in fixed mode
    if (field.nullable && (value === null || value === undefined)) {
      // fixed mode requires both coordinates
      if (field.key === 'weather.location.latitude' || field.key === 'weather.location.longitude') {
        const mode = draft ? getPath(draft, 'weather.location.mode') : null;
        if (mode === 'fixed') return 'fixed 模式下需同时填写纬度与经度';
      }
      return null;
    }
    if (isEmptyValue(value)) return '不能为空';
    if (typeof value !== 'number' || !Number.isFinite(value)) return '需为数值';
    if (field.min !== undefined && value < field.min - 1e-9) {
      if (field.max !== undefined) {
        const kind = isIntegerLike(field) ? '整数' : '数值';
        return `需为 ${field.min}–${field.max} 的${kind}`;
      }
      return `需为不小于 ${field.min} 的数值`;
    }
    if (field.max !== undefined && value > field.max + 1e-9) {
      if (field.min !== undefined) {
        const kind = isIntegerLike(field) ? '整数' : '数值';
        return `需为 ${field.min}–${field.max} 的${kind}`;
      }
      return `需为不大于 ${field.max} 的数值`;
    }
    // integer check for known integer fields
    if (isIntegerLike(field) && !Number.isInteger(value)) {
      return `需为 ${field.min ?? ''}${field.max !== undefined ? `–${field.max}` : ''} 的整数`.replace(/^需为 –/, '需为 ').trim();
    }
    // special minimum for panel.animation.durationMs is 400
    if (field.key === 'panel.animation.durationMs' && value < 400) return '需为不小于 400 的数值';
    return null;
  }
  if (field.type === 'text' || field.type === 'password') {
    // menu.terminal is optional (empty means auto-detect)
    if (field.key === 'menu.terminal') {
      if (value !== undefined && value !== null && typeof value !== 'string') return '需为字符串';
      return null;
    }
    // apiHost has HTTPS hostname rule
    if (field.key === 'apiHost') {
      if (isEmptyValue(value)) return '不能为空';
      const raw = String(value).trim();
      try {
        const url = new URL(raw.includes('://') ? raw : `https://${raw}`);
        if (url.protocol !== 'https:' || url.username || url.password || url.port || url.pathname !== '/' || url.search || url.hash) {
          return '需为 HTTPS 域名，如 your-host.qweatherapi.com';
        }
        if (!url.hostname.includes('.')) return '需为 HTTPS 域名，如 your-host.qweatherapi.com';
      } catch {
        return '需为 HTTPS 域名，如 your-host.qweatherapi.com';
      }
      return null;
    }
    if (field.key === 'apiKey') {
      // credentials save handles empty-as-keep-existing, but field validation for draft is still required when creating new
      // Allow empty here; required check is done on saveCredentials path. For live validation we show hint only if host filled.
      if (isEmptyValue(value)) return null; // keep-existing allowed; required enforced on save when configured===false
      return null;
    }
    // fallbackLocationId / tideStationId / command subfields are nonEmpty
    if (isEmptyValue(value)) return '不能为空';
    if (typeof value !== 'string') return '需为字符串';
    return null;
  }
  if (field.type === 'commands') {
    const list = value;
    if (!Array.isArray(list)) return '需为数组';
    // per-row checks are handled by validateCommandField
    return null;
  }
  return null;
}

export function validateCommandField(subfield, value) {
  if (!subfield) return null;
  if (subfield.type === 'enum') {
    const allowed = (subfield.options ?? []).map((o) => o.value);
    if (!allowed.includes(value)) return `需为 ${allowed.join(' / ')}`;
    return null;
  }
  if (isEmptyValue(value)) return '不能为空';
  return null;
}

// Validate an entire draft object; returns Map<key, message> for every
// invalid field. `credentials` is optional extra draft for apiHost/apiKey.
export function validateDraft(draft, { credentials } = {}) {
  const errors = new Map();
  for (const group of SETTINGS_GROUPS) {
    if (group.static) continue;
    for (const field of group.fields) {
      if (field.type === 'commands') {
        const list = getPath(draft, field.key) ?? [];
        if (!Array.isArray(list)) {
          errors.set(field.key, '需为数组');
          continue;
        }
        list.forEach((entry, idx) => {
          if (!entry || typeof entry !== 'object') {
            errors.set(`${field.key}[${idx}]`, '需为对象');
            return;
          }
          for (const sub of field.fields ?? []) {
            const v = entry[sub.key];
            const msg = validateCommandField(sub, v);
            if (msg) errors.set(`${field.key}[${idx}].${sub.key}`, msg);
          }
        });
        continue;
      }
      if (field.external) {
        // external credentials are not part of config.json; only validate when
        // caller supplies a credentials object (e.g. live UI values)
        if (!credentials) continue;
        const v = credentials[field.key];
        const msg = validateField(field, v, draft);
        if (msg) errors.set(field.key, msg);
        continue;
      }
      const value = getPath(draft, field.key);
      const msg = validateField(field, value, draft);
      if (msg) errors.set(field.key, msg);
    }
  }
  // cross-field: fixed mode requires both coordinates (also covered per-field but ensure both flagged)
  const mode = getPath(draft, 'weather.location.mode');
  if (mode === 'fixed') {
    const lat = getPath(draft, 'weather.location.latitude');
    const lng = getPath(draft, 'weather.location.longitude');
    if (lat === null || lat === undefined) errors.set('weather.location.latitude', 'fixed 模式下需同时填写纬度与经度');
    if (lng === null || lng === undefined) errors.set('weather.location.longitude', 'fixed 模式下需同时填写纬度与经度');
    if (typeof lat === 'number' && (lat < -90 || lat > 90)) errors.set('weather.location.latitude', '需为 -90–90 的数值');
    if (typeof lng === 'number' && (lng < -180 || lng > 180)) errors.set('weather.location.longitude', '需为 -180–180 的数值');
  }
  return errors;
}

// Translate backend English errors to concise Chinese using field metadata.
// Falls back to original message if no mapping found.
export function translateBackendError(message) {
  if (!message || typeof message !== 'string') return String(message);
  // Try to extract field path prefix like "panel.shadowIntensity must ..."
  const mustIdx = message.indexOf(' must ');
  let path = message;
  if (message.startsWith('Unknown configuration field: ')) {
    path = message.slice('Unknown configuration field: '.length);
    const key = path.trim().split(/[.\[]/)[0] + (path.includes('.') ? '.' + path.split('.')[1] : '');
    // Map unknown field to generic
    return '未知字段：' + path;
  }
  if (mustIdx !== -1) path = message.slice(0, mustIdx).trim();
  // Normalize "menu.customCommands[0].label must ..." -> "menu.customCommands"
  const baseKey = path.split('[')[0];
  // Find field by baseKey or exact path
  let field = null;
  for (const g of SETTINGS_GROUPS) {
    for (const f of g.fields) {
      if (f.key === path || f.key === baseKey) field = f;
      if (path.startsWith(f.key + '.') || path.startsWith(f.key + '[')) field = f;
    }
  }
  if (field) {
    // Re-run validate logic to get Chinese message for current draft? For now return generic range hint
    if (message.includes('must be between')) {
      if (field.min !== undefined && field.max !== undefined) {
        const kind = isIntegerLike(field) ? '整数' : '数值';
        return `需为 ${field.min}–${field.max} 的${kind}`;
      }
      return '超出允许范围';
    }
    if (message.includes('must be a finite number')) {
      if (field.min !== undefined && field.max !== undefined) {
        const kind = isIntegerLike(field) ? '整数' : '数值';
        return `需为 ${field.min}–${field.max} 的${kind}`;
      }
      if (message.includes('at least 0')) return '需为不小于 0 的数值';
      if (message.includes('greater than 0')) return '需为大于 0 的数值';
      return '需为数值';
    }
    if (message.includes('must be a non-empty string')) return '不能为空';
    if (message.includes('must be a string')) return '需为字符串';
    if (message.includes('must be a boolean')) return '需为布尔值';
    if (message.includes('must be') && field.type === 'enum') {
      const allowed = (field.options ?? []).map((o) => o.value).join(' / ');
      if (allowed) return `需为 ${allowed}`;
    }
    if (message.includes('apiHost')) return '需为 HTTPS 域名，如 your-host.qweatherapi.com';
    if (message.includes('apiKey')) return '不能为空';
  }
  // Fallback: map common English fragments
  if (message.includes('Duplicate menu command id')) return '命令 ID 重复';
  if (message.includes('Menu command id is reserved')) return '命令 ID 为保留字';
  if (message.includes('fixed mode requires both latitude and longitude')) return 'fixed 模式下需同时填写纬度与经度';
  if (message.includes('must be an integer between')) return '需为整数且在允许范围内';
  return message;
}
